# Pre-commit hooks for CreatorFlow
# Install with: pip install pre-commit && pre-commit install

repos:
  # Gitleaks - Secret Detection
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
        name: Detect secrets with Gitleaks
        description: Detect hardcoded secrets using Gitleaks
        entry: gitleaks
        language: golang
        types: [text]

  # General code quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: detect-private-key
        name: Detect private keys
      - id: detect-aws-credentials
        name: Detect AWS credentials

  # TypeScript/JavaScript linting
  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: bunx eslint --fix
        language: node
        types: [javascript, jsx, ts, tsx]
        require_serial: false
        additional_dependencies: []
        minimum_pre_commit_version: 0.15.0

  # Environment file check
  - repo: local
    hooks:
      - id: check-env-files
        name: Check for .env files
        entry: bash -c 'if find . -name ".env" -not -path "./node_modules/*" -not -name "*.example" | grep -q .; then echo "ERROR: .env files found! Never commit .env files."; exit 1; fi'
        language: system
        pass_filenames: false
        always_run: true
